version: '3.2'
services:
  api:
    image: xahlijah/afriqom-api:v1.0.0
    environment:
      - DATABASE_SERVER=databoardserver.mysql.database.azure.com
      - DATABASE_NAME=afriqom
      - DATABASE_USER=databoard_admin
      - DATABASE_PASSWORD=Sqlserver5
      - DATABASE_PORT=3306
      - ROLES_DATABASE_NAME=afriqom_roles
    volumes:
      - ./logs/:/logs/
      - ./cdn/:/app/api/cdn/
  web:
    image: xahlijah/afriqom-web:v1.0.0
  nginx:
    image: xahlijah/afriqom-nginx:v1.0.0
    ports:
      - 80:80
      - 443:443