version: '3.2'
services:
  api:
    image: xahlijah/afriqom-api:v1.0.0
    environment:
      - DATABASE_SERVER=''
      - DATABASE_NAME=''
      - DATABASE_USER=''
      - DATABASE_PASSWORD=''
      - DATABASE_PORT=3306
      - ROLES_DATABASE_NAME=''
    volumes:
      - ./logs/:/logs/
      - ./cdn/:/app/api/cdn/
  web:
    image: xahlijah/afriqom-web:v1.0.0
  nginx:
    image: xahlijah/afriqom-nginx:v1.0.1
    ports:
      - 80:80
      - 443:443